---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kbot
  namespace: kbot-tf-flux
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/yevgen-grytsay/kbot
